[tools]
# =================================================================================================
# Project Tools
# =================================================================================================
"aqua:helm/helm" = "4.0.5"
"aqua:norwoodj/helm-docs" = "1.14"
"aqua:dadav/helm-schema" = "0.20.0"

# =================================================================================================
# Misc Tools
# =================================================================================================
"aqua:kubernetes/kubectl" = "latest"
"aqua:kubernetes/minikube" = "latest"
"aqua:derailed/k9s" = "latest"

# =================================================================================================
# CI Tools
# =================================================================================================
"aqua:rhysd/actionlint" = "1"
"npm:@commitlint/cli" = "20"
